version: '3.1'

services: 
  sqlmap:
    container_name: sqlmap
    restart: always
    network_mode: host
    image: tangx/sqlmap:latest
    volumes:
      - ./data/:/root/.local/:rw
      - ./target:/data/target:rw
    ports:
      - 30080:80
    command:
      - tail
      - -f
      - /dev/stdout