name: sqlmap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

on:
  schedule:
    - cron: '10 3 * * *'

jobs:
  server:
    name: sqlmap
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}  
  
    - name: show env
      run: env && pwd
    - name: ls -al 
      run: ls -al 

    - name: use checkout
      uses:  actions/checkout@v2
    - name: build and push
      run: |
        docker-compose build
        docker-compose push
